name:                Hasktorch
version:             0.1.0.0
github:              "githubuser/Hasktorch"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Hasktorch#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  session3-linear-regression:
    main: LinearRegression.hs
    source-dirs: Session3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - Hasktorch
    - hasktorch-tools
    - hasktorch == 0.2.0.0
    other-modules: []
  
  session3-graduate-admission-linear:
    main: GraduateAdmissionLinear.hs
    source-dirs: Session3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - Hasktorch
      - hasktorch-tools
      - hasktorch == 0.2.0.0
      - cassava
      - bytestring
      - vector
      - nlp-tools
    other-modules: []
  
  session3-multiple-regression:
    main: MultipleRegression.hs
    source-dirs: Session3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - Hasktorch
      - hasktorch-tools
      - hasktorch == 0.2.0.0
      - cassava
      - bytestring
      - vector
      - nlp-tools
    other-modules: []

  session3-graduate-admission:
    main: GraduateAdmission.hs
    source-dirs: Session3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - Hasktorch
      - hasktorch-tools
      - hasktorch == 0.2.0.0
      - cassava
      - bytestring
      - vector
      - nlp-tools
    other-modules: []

  session4-perceptron-andgate:
    main: PerceptronAndGate.hs
    source-dirs: Session4
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - Hasktorch
      - hasktorch-tools
      - hasktorch == 0.2.0.0
      - cassava
      - bytestring
      - vector
      - nlp-tools
      - random
    other-modules: []

  session4-perceptron-mlpxor:
    main: MlpXor.hs
    source-dirs: Session4
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - Hasktorch
      - hasktorch-tools
      - hasktorch == 0.2.0.0
      - cassava
      - bytestring
      - vector
      - nlp-tools
      - random
    other-modules: []

  session4-perceptron-mlpxor-sigmoid:
    main: MlpXor_sigmoid.hs
    source-dirs: Session4
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - Hasktorch
      - hasktorch-tools
      - hasktorch == 0.2.0.0
      - cassava
      - bytestring
      - vector
      - nlp-tools
      - random
    other-modules: []
  
  session4-perceptron-mlpxor-step:
    main: MlpXor_step.hs
    source-dirs: Session4
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - Hasktorch
      - hasktorch-tools
      - hasktorch == 0.2.0.0
      - cassava
      - bytestring
      - vector
      - nlp-tools
      - random
    other-modules: []

tests:
  Hasktorch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hasktorch
